### ISSUE TITLE
Can't configure app context with configure_sentry()

### ISSUE THREAD

**Issue by egnor** [jcpsantiago/sentryR#24]
In [this code](https://github.com/EduSemensati/sentryR/blob/b4d0767736f7ebc3b4916a078c6c4d0a44d59890/R/core.R#L74C21-L74C21), any extra parameters are appended to the payload skeleton which is used as the base for requests... BUT if additional `contexts` (especially `contexts$app`) are added, they will be appended to the existing contexts in the list, and the JSON serializer will rename them and thus they will get lost.

Probably better to use `utils::modifyList` to append the user's parameters to the system defaults, rather than just including the `...` at the end of the system default list?

**Comment by jcpsantiago** [comment]
Interesting one! In which situation would you want to add multiple `app` contexts? Asking because I've only ever used one, so I'm curious about your use-case. In any case your proposal makes sense!

If you have time/want to contribute go ahead a make a PR. I'll review it/we can work together on it :) Otherwise give me some time and I'll get to it in the coming weeks.

**Comment by egnor** [comment]
I don't want to set _multiple_ app contexts, I just want to set one value! I like to set up as much as possible at the start, so I initialize with something like this:

```
...
sentryR::configure_sentry(
  dsn = Sys.getenv(dsn_var),
  app_name = my_service_name(),
  logger = "mylibrary::log_error_to_sentry",
  server_name = sys_info["nodename"],
  environment = environment,
  modules = module_list,
  extra = extra,
  user = list(username = sys_info["user"])
)
```

When I actually capture an exception I do this:
```
sentryR::capture_exception(
  error = error,
  message = as.character(error),
  contexts = list(app = list(app_identifier = "My Cool App")),
  extra = list(
    drake_target = drake_target,  # my own dynamic stuff
    drake_plan = drake_plan
  )
)
```

Since it's static, I'd like to move the `contexts = list(app = list(app_identifier = "My Cool App"))` to the `configure_sentry()` call, but because of this issue I cannot. Does that make sense?

I can prepare a PR to send you.
