### ISSUE TITLE
What is the `bunny` package?

### ISSUE THREAD

**Issue by egnor** [jcpsantiago/sentryR#28]
In `ghcard.R` ([one copy](https://github.com/EduSemensati/sentryR/blob/master/docs/reference/figures/ghcard.R), [another copy](https://github.com/EduSemensati/sentryR/blob/master/man/figures/ghcard.R)), reference is made to a `bunny` library:

```
library(magick)
library(bunny)

img_hex_gh <- image_read("man/figures/logo.png") %>%
  image_scale("400x400")

gh_logo <- bunny::github %>%
  image_scale("50x50")
...
```

I cannot find this `bunny` library on CRAN or elsewhere? Of course this file appears to exist only to regenerate the logo image, which is also checked in, so it's not really a big deal, but `renv` flagged it as a reference that isn't listed as a dependency and I wasn't sure what that's all about.

**Comment by egnor** [comment]
Ah, it seems like it's https://github.com/dmi3kno/bunny ? Since it's not in CRAN, maybe that github link can be in the list of suggested packages?

**Comment by jcpsantiago** [comment]
it's a package used to created the hexagon logo, and also the Github "social card" you see if you paste this repo's url into social media:
![Screenshot 2023-08-11 at 10 47 39](https://github.com/EduSemensati/sentryR/assets/789796/9fdabed0-4aa0-4dba-b215-38c0dbff6c78)

Will review your PR thanks!
