### ISSUE TITLE
Ambiguous error with Plumber

### ISSUE THREAD

**Issue by qbunt** [jcpsantiago/sentryR#31]
Implemented exactly as shown in the docs with plumber, I'm getting the following out of R when new requests come into plumber

```
Error in z(...): unused arguments (req = <environment>, res = <environment>)
```
I'm assuming something has changed with the payload that Sentry expects or something is now broken.

**Comment by qbunt** [comment]
@jcpsantiago should I be using this library anymore or is it way out of date?

**Comment by jcpsantiago** [comment]
Hey, I'm still maintaining this library. The version in CRAN hasn't changed in a while. Could you please share which versions of R, sentryR and plumber you're using?

**Comment by qbunt** [comment]
@jcpsantiago 🤔 I don't think there's a version in cran right now? [You might want to check cran](https://cran.r-project.org/web/packages/sentryR/index.html), looks like the build there has been archived.

**Comment by jcpsantiago** [comment]
Oh! Thanks for letting me know! The CRAN version was attached to my previous company's email. I'll release again.

**Comment by qbunt** [comment]
Looks like this is still unavailable. Any way you could automate a release or just do one manually?

**Comment by jcpsantiago** [comment]
Hey @qbunt I started the back-and-forth with CRAN to release it. Because it was archived before it may take a bit more time.

**Comment by jcpsantiago** [comment]
@qbunt sentryR is now re-released on CRAN.
